# netlify.toml
[build]
  publish = "/"
  command = "echo 'No build command needed for static site'"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  # Environment variables will be set in the Netlify UI
  # SUPABASE_ANON_KEY = "your-supabase-anon-key"
