# netlify.toml
[build]
  publish = "/"
  command = "echo 'No build command needed for static site'"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  # Environment variables will be set in the Netlify UI
  # SUPABASE_ANON_KEY = "your-supabase-anon-key"

[functions.process-label]
  # Explicitly include environment variables for this function
  # The actual values will be set in the Netlify UI
  included_files = ["**"]
  external_node_modules = ["node-fetch", "form-data"]
  # Increase timeout to 26 seconds (max allowed is 26 seconds)
  timeout = 26


[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  